version: "3.8"

services:
  db:
    container_name: posgressDB
    image: postgres:15.1
    volumes:
    # volumen externo:bd page
      # - postgresDB:/var/lib/postgresql/data
      - ./posgress:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=12345
      - PGADMIN_DEFAULT_EMAIL=superman@google.com

# volumes:
#  postgresDB:
#    external: true